### ISSUE TITLE
Create end user documentation on how to properly use the test-api

### ISSUE THREAD

**Issue by jamesrdi** [kadai-io/kadai#42]
In order to make the test-api easier to use for our users, we want to create an end user documentation on how to properly use the test-api.

**Comment by ryzheboka** [comment]
Hi @jamesrdi,
Could you link the PR that completed this issue? Or add an explanation why this issue was completed?

**Comment by bruderj15** [comment]
Probably because of https://github.com/kadai-io/kadai/issues/41.
